
package cliente.prestamo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PrestamoPublishService", targetNamespace = "http://publicadores/", wsdlLocation = "http://localhost:18020/prestamo?wsdl")
public class PrestamoPublishService
    extends Service
{

    private final static URL PRESTAMOPUBLISHSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRESTAMOPUBLISHSERVICE_EXCEPTION;
    private final static QName PRESTAMOPUBLISHSERVICE_QNAME = new QName("http://publicadores/", "PrestamoPublishService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:18020/prestamo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRESTAMOPUBLISHSERVICE_WSDL_LOCATION = url;
        PRESTAMOPUBLISHSERVICE_EXCEPTION = e;
    }

    public PrestamoPublishService() {
        super(__getWsdlLocation(), PRESTAMOPUBLISHSERVICE_QNAME);
    }

    public PrestamoPublishService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRESTAMOPUBLISHSERVICE_QNAME, features);
    }

    public PrestamoPublishService(URL wsdlLocation) {
        super(wsdlLocation, PRESTAMOPUBLISHSERVICE_QNAME);
    }

    public PrestamoPublishService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRESTAMOPUBLISHSERVICE_QNAME, features);
    }

    public PrestamoPublishService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PrestamoPublishService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PrestamoPublish
     */
    @WebEndpoint(name = "PrestamoPublishPort")
    public PrestamoPublish getPrestamoPublishPort() {
        return super.getPort(new QName("http://publicadores/", "PrestamoPublishPort"), PrestamoPublish.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PrestamoPublish
     */
    @WebEndpoint(name = "PrestamoPublishPort")
    public PrestamoPublish getPrestamoPublishPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://publicadores/", "PrestamoPublishPort"), PrestamoPublish.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRESTAMOPUBLISHSERVICE_EXCEPTION!= null) {
            throw PRESTAMOPUBLISHSERVICE_EXCEPTION;
        }
        return PRESTAMOPUBLISHSERVICE_WSDL_LOCATION;
    }

}
