
package cliente.listarPrestamosZona;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ListarPrestamosZonaPublishService", targetNamespace = "http://publicadores/", wsdlLocation = "http://localhost:18027/listarPrestamosZona?wsdl")
public class ListarPrestamosZonaPublishService
    extends Service
{

    private final static URL LISTARPRESTAMOSZONAPUBLISHSERVICE_WSDL_LOCATION;
    private final static WebServiceException LISTARPRESTAMOSZONAPUBLISHSERVICE_EXCEPTION;
    private final static QName LISTARPRESTAMOSZONAPUBLISHSERVICE_QNAME = new QName("http://publicadores/", "ListarPrestamosZonaPublishService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:18027/listarPrestamosZona?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LISTARPRESTAMOSZONAPUBLISHSERVICE_WSDL_LOCATION = url;
        LISTARPRESTAMOSZONAPUBLISHSERVICE_EXCEPTION = e;
    }

    public ListarPrestamosZonaPublishService() {
        super(__getWsdlLocation(), LISTARPRESTAMOSZONAPUBLISHSERVICE_QNAME);
    }

    public ListarPrestamosZonaPublishService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LISTARPRESTAMOSZONAPUBLISHSERVICE_QNAME, features);
    }

    public ListarPrestamosZonaPublishService(URL wsdlLocation) {
        super(wsdlLocation, LISTARPRESTAMOSZONAPUBLISHSERVICE_QNAME);
    }

    public ListarPrestamosZonaPublishService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LISTARPRESTAMOSZONAPUBLISHSERVICE_QNAME, features);
    }

    public ListarPrestamosZonaPublishService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ListarPrestamosZonaPublishService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ListarPrestamosZonaPublish
     */
    @WebEndpoint(name = "ListarPrestamosZonaPublishPort")
    public ListarPrestamosZonaPublish getListarPrestamosZonaPublishPort() {
        return super.getPort(new QName("http://publicadores/", "ListarPrestamosZonaPublishPort"), ListarPrestamosZonaPublish.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ListarPrestamosZonaPublish
     */
    @WebEndpoint(name = "ListarPrestamosZonaPublishPort")
    public ListarPrestamosZonaPublish getListarPrestamosZonaPublishPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://publicadores/", "ListarPrestamosZonaPublishPort"), ListarPrestamosZonaPublish.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LISTARPRESTAMOSZONAPUBLISHSERVICE_EXCEPTION!= null) {
            throw LISTARPRESTAMOSZONAPUBLISHSERVICE_EXCEPTION;
        }
        return LISTARPRESTAMOSZONAPUBLISHSERVICE_WSDL_LOCATION;
    }

}
