
package cliente.altaDonacionEspecial;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AltaDonacionEspecialPublishService", targetNamespace = "http://publicadores/", wsdlLocation = "http://localhost:18022/altaDonacionEspecial?wsdl")
public class AltaDonacionEspecialPublishService
    extends Service
{

    private final static URL ALTADONACIONESPECIALPUBLISHSERVICE_WSDL_LOCATION;
    private final static WebServiceException ALTADONACIONESPECIALPUBLISHSERVICE_EXCEPTION;
    private final static QName ALTADONACIONESPECIALPUBLISHSERVICE_QNAME = new QName("http://publicadores/", "AltaDonacionEspecialPublishService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:18022/altaDonacionEspecial?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ALTADONACIONESPECIALPUBLISHSERVICE_WSDL_LOCATION = url;
        ALTADONACIONESPECIALPUBLISHSERVICE_EXCEPTION = e;
    }

    public AltaDonacionEspecialPublishService() {
        super(__getWsdlLocation(), ALTADONACIONESPECIALPUBLISHSERVICE_QNAME);
    }

    public AltaDonacionEspecialPublishService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ALTADONACIONESPECIALPUBLISHSERVICE_QNAME, features);
    }

    public AltaDonacionEspecialPublishService(URL wsdlLocation) {
        super(wsdlLocation, ALTADONACIONESPECIALPUBLISHSERVICE_QNAME);
    }

    public AltaDonacionEspecialPublishService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ALTADONACIONESPECIALPUBLISHSERVICE_QNAME, features);
    }

    public AltaDonacionEspecialPublishService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AltaDonacionEspecialPublishService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AltaDonacionEspecialPublish
     */
    @WebEndpoint(name = "AltaDonacionEspecialPublishPort")
    public AltaDonacionEspecialPublish getAltaDonacionEspecialPublishPort() {
        return super.getPort(new QName("http://publicadores/", "AltaDonacionEspecialPublishPort"), AltaDonacionEspecialPublish.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AltaDonacionEspecialPublish
     */
    @WebEndpoint(name = "AltaDonacionEspecialPublishPort")
    public AltaDonacionEspecialPublish getAltaDonacionEspecialPublishPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://publicadores/", "AltaDonacionEspecialPublishPort"), AltaDonacionEspecialPublish.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ALTADONACIONESPECIALPUBLISHSERVICE_EXCEPTION!= null) {
            throw ALTADONACIONESPECIALPUBLISHSERVICE_EXCEPTION;
        }
        return ALTADONACIONESPECIALPUBLISHSERVICE_WSDL_LOCATION;
    }

}
