
package cliente.consultarDonacionPorFecha;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConsultaDonacionYFechaPublish", targetNamespace = "http://publicadores/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConsultaDonacionYFechaPublish {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns cliente.consultarDonacionPorFecha.DtMaterialArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/ConsultaDonacionYFechaPublish/consultarDonacionPorFechaRequest", output = "http://publicadores/ConsultaDonacionYFechaPublish/consultarDonacionPorFechaResponse")
    public DtMaterialArray consultarDonacionPorFecha(
        @WebParam(name = "arg0", partName = "arg0")
        XMLGregorianCalendar arg0,
        @WebParam(name = "arg1", partName = "arg1")
        XMLGregorianCalendar arg1);

}
