
package cliente.modificarTodoPrestamo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ModificarTodoPrestamoPublishService", targetNamespace = "http://publicadores/", wsdlLocation = "http://localhost:18028/modificarTodoPrestamo?wsdl")
public class ModificarTodoPrestamoPublishService
    extends Service
{

    private final static URL MODIFICARTODOPRESTAMOPUBLISHSERVICE_WSDL_LOCATION;
    private final static WebServiceException MODIFICARTODOPRESTAMOPUBLISHSERVICE_EXCEPTION;
    private final static QName MODIFICARTODOPRESTAMOPUBLISHSERVICE_QNAME = new QName("http://publicadores/", "ModificarTodoPrestamoPublishService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:18028/modificarTodoPrestamo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MODIFICARTODOPRESTAMOPUBLISHSERVICE_WSDL_LOCATION = url;
        MODIFICARTODOPRESTAMOPUBLISHSERVICE_EXCEPTION = e;
    }

    public ModificarTodoPrestamoPublishService() {
        super(__getWsdlLocation(), MODIFICARTODOPRESTAMOPUBLISHSERVICE_QNAME);
    }

    public ModificarTodoPrestamoPublishService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MODIFICARTODOPRESTAMOPUBLISHSERVICE_QNAME, features);
    }

    public ModificarTodoPrestamoPublishService(URL wsdlLocation) {
        super(wsdlLocation, MODIFICARTODOPRESTAMOPUBLISHSERVICE_QNAME);
    }

    public ModificarTodoPrestamoPublishService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MODIFICARTODOPRESTAMOPUBLISHSERVICE_QNAME, features);
    }

    public ModificarTodoPrestamoPublishService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ModificarTodoPrestamoPublishService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ModificarTodoPrestamoPublish
     */
    @WebEndpoint(name = "ModificarTodoPrestamoPublishPort")
    public ModificarTodoPrestamoPublish getModificarTodoPrestamoPublishPort() {
        return super.getPort(new QName("http://publicadores/", "ModificarTodoPrestamoPublishPort"), ModificarTodoPrestamoPublish.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ModificarTodoPrestamoPublish
     */
    @WebEndpoint(name = "ModificarTodoPrestamoPublishPort")
    public ModificarTodoPrestamoPublish getModificarTodoPrestamoPublishPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://publicadores/", "ModificarTodoPrestamoPublishPort"), ModificarTodoPrestamoPublish.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MODIFICARTODOPRESTAMOPUBLISHSERVICE_EXCEPTION!= null) {
            throw MODIFICARTODOPRESTAMOPUBLISHSERVICE_EXCEPTION;
        }
        return MODIFICARTODOPRESTAMOPUBLISHSERVICE_WSDL_LOCATION;
    }

}
