
package cliente.modificarTodoPrestamo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ModificarTodoPrestamoPublish", targetNamespace = "http://publicadores/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ModificarTodoPrestamoPublish {


    /**
     * 
     * @return
     *     returns cliente.modificarTodoPrestamo.DtMaterialArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/ModificarTodoPrestamoPublish/getListadoMaterialesRequest", output = "http://publicadores/ModificarTodoPrestamoPublish/getListadoMaterialesResponse")
    public DtMaterialArray getListadoMateriales();

    /**
     * 
     * @return
     *     returns cliente.modificarTodoPrestamo.DtLectorArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/ModificarTodoPrestamoPublish/getListadoLectoresRequest", output = "http://publicadores/ModificarTodoPrestamoPublish/getListadoLectoresResponse")
    public DtLectorArray getListadoLectores();

    /**
     * 
     * @return
     *     returns cliente.modificarTodoPrestamo.DtBibliotecarioArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/ModificarTodoPrestamoPublish/getListadoBibliotecariosRequest", output = "http://publicadores/ModificarTodoPrestamoPublish/getListadoBibliotecariosResponse")
    public DtBibliotecarioArray getListadoBibliotecarios();

    /**
     * 
     * @return
     *     returns cliente.modificarTodoPrestamo.DtPrestamoArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/ModificarTodoPrestamoPublish/listarPrestamosRequest", output = "http://publicadores/ModificarTodoPrestamoPublish/listarPrestamosResponse")
    public DtPrestamoArray listarPrestamos();

    /**
     * 
     * @param arg0
     * @throws PrestamoNoExisteExcepcion_Exception
     */
    @WebMethod
    @Action(input = "http://publicadores/ModificarTodoPrestamoPublish/modificarPrestamoRequest", output = "http://publicadores/ModificarTodoPrestamoPublish/modificarPrestamoResponse", fault = {
        @FaultAction(className = PrestamoNoExisteExcepcion_Exception.class, value = "http://publicadores/ModificarTodoPrestamoPublish/modificarPrestamo/Fault/PrestamoNoExisteExcepcion")
    })
    public void modificarPrestamo(
        @WebParam(name = "arg0", partName = "arg0")
        DtPrestamo arg0)
        throws PrestamoNoExisteExcepcion_Exception
    ;

}
