
package cliente.modificarTodoPrestamo;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "PrestamoNoExisteExcepcion", targetNamespace = "http://publicadores/")
public class PrestamoNoExisteExcepcion_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private PrestamoNoExisteExcepcion faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public PrestamoNoExisteExcepcion_Exception(String message, PrestamoNoExisteExcepcion faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public PrestamoNoExisteExcepcion_Exception(String message, PrestamoNoExisteExcepcion faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: cliente.modificarTodoPrestamo.PrestamoNoExisteExcepcion
     */
    public PrestamoNoExisteExcepcion getFaultInfo() {
        return faultInfo;
    }

}
