
package cliente.altaLector;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "AltaLectorPublish", targetNamespace = "http://publicadores/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AltaLectorPublish {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @throws LectorRepetidoExcepcion_Exception
     */
    @WebMethod
    @Action(input = "http://publicadores/AltaLectorPublish/altaLectorRequest", output = "http://publicadores/AltaLectorPublish/altaLectorResponse", fault = {
        @FaultAction(className = LectorRepetidoExcepcion_Exception.class, value = "http://publicadores/AltaLectorPublish/altaLector/Fault/LectorRepetidoExcepcion")
    })
    public void altaLector(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        XMLGregorianCalendar arg4,
        @WebParam(name = "arg5", partName = "arg5")
        Zona arg5)
        throws LectorRepetidoExcepcion_Exception
    ;

}
