
package cliente.altaLector;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "LectorRepetidoExcepcion", targetNamespace = "http://publicadores/")
public class LectorRepetidoExcepcion_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private LectorRepetidoExcepcion faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public LectorRepetidoExcepcion_Exception(String message, LectorRepetidoExcepcion faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public LectorRepetidoExcepcion_Exception(String message, LectorRepetidoExcepcion faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: cliente.altaLector.LectorRepetidoExcepcion
     */
    public LectorRepetidoExcepcion getFaultInfo() {
        return faultInfo;
    }

}
