
package cliente.modificarZonaLector;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ModificarZonaLectorPublish", targetNamespace = "http://publicadores/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ModificarZonaLectorPublish {


    /**
     * 
     * @param arg1
     * @param arg0
     * @throws LectorNoExisteExcepcion_Exception
     */
    @WebMethod
    @Action(input = "http://publicadores/ModificarZonaLectorPublish/modificarZonaLectorRequest", output = "http://publicadores/ModificarZonaLectorPublish/modificarZonaLectorResponse", fault = {
        @FaultAction(className = LectorNoExisteExcepcion_Exception.class, value = "http://publicadores/ModificarZonaLectorPublish/modificarZonaLector/Fault/LectorNoExisteExcepcion")
    })
    public void modificarZonaLector(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        Zona arg1)
        throws LectorNoExisteExcepcion_Exception
    ;

    /**
     * 
     * @return
     *     returns cliente.modificarZonaLector.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/ModificarZonaLectorPublish/listarNombresLectoresRequest", output = "http://publicadores/ModificarZonaLectorPublish/listarNombresLectoresResponse")
    public StringArray listarNombresLectores();

}
