
package cliente.prestamo;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "PrestamoPublish", targetNamespace = "http://publicadores/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PrestamoPublish {


    /**
     * 
     * @param arg0
     * @return
     *     returns cliente.prestamo.DtMaterialConPrestamoArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PrestamoPublish/getMaterialesConPrestamoRequest", output = "http://publicadores/PrestamoPublish/getMaterialesConPrestamoResponse")
    public DtMaterialConPrestamoArray getMaterialesConPrestamo(
        @WebParam(name = "arg0", partName = "arg0")
        DtLector arg0);

    /**
     * 
     * @return
     *     returns cliente.prestamo.DtMaterialConPrestamoArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PrestamoPublish/getMaterialesConPrestamoTodosRequest", output = "http://publicadores/PrestamoPublish/getMaterialesConPrestamoTodosResponse")
    public DtMaterialConPrestamoArray getMaterialesConPrestamoTodos();

    /**
     * 
     * @return
     *     returns cliente.prestamo.DtMaterialArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PrestamoPublish/getListadoMaterialesRequest", output = "http://publicadores/PrestamoPublish/getListadoMaterialesResponse")
    public DtMaterialArray getListadoMateriales();

    /**
     * 
     * @return
     *     returns cliente.prestamo.AnyTypeArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PrestamoPublish/consultarPrestamosComunesRequest", output = "http://publicadores/PrestamoPublish/consultarPrestamosComunesResponse")
    public AnyTypeArray consultarPrestamosComunes();

    /**
     * 
     * @param arg0
     * @return
     *     returns cliente.prestamo.DtPrestamoArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PrestamoPublish/consultarPrestamosBibliotecarioRequest", output = "http://publicadores/PrestamoPublish/consultarPrestamosBibliotecarioResponse")
    public DtPrestamoArray consultarPrestamosBibliotecario(
        @WebParam(name = "arg0", partName = "arg0")
        DtBibliotecario arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns cliente.prestamo.DtPrestamoSimpleArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PrestamoPublish/getPrestamosActivosPorLectorRequest", output = "http://publicadores/PrestamoPublish/getPrestamosActivosPorLectorResponse")
    public DtPrestamoSimpleArray getPrestamosActivosPorLector(
        @WebParam(name = "arg0", partName = "arg0")
        DtLector arg0);

    /**
     * 
     * @return
     *     returns cliente.prestamo.DtBibliotecarioArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PrestamoPublish/getListadoBibliotecariosRequest", output = "http://publicadores/PrestamoPublish/getListadoBibliotecariosResponse")
    public DtBibliotecarioArray getListadoBibliotecarios();

    /**
     * 
     * @return
     *     returns cliente.prestamo.DtLectorArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PrestamoPublish/getListadoLectoresRequest", output = "http://publicadores/PrestamoPublish/getListadoLectoresResponse")
    public DtLectorArray getListadoLectores();

    /**
     * 
     * @param arg0
     * @throws PrestamoYaExisteExcepcion_Exception
     */
    @WebMethod
    @Action(input = "http://publicadores/PrestamoPublish/altaPrestamoRequest", output = "http://publicadores/PrestamoPublish/altaPrestamoResponse", fault = {
        @FaultAction(className = PrestamoYaExisteExcepcion_Exception.class, value = "http://publicadores/PrestamoPublish/altaPrestamo/Fault/PrestamoYaExisteExcepcion")
    })
    public void altaPrestamo(
        @WebParam(name = "arg0", partName = "arg0")
        DtPrestamo arg0)
        throws PrestamoYaExisteExcepcion_Exception
    ;

    /**
     * 
     * @return
     *     returns cliente.prestamo.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/PrestamoPublish/getNombresLectoresRequest", output = "http://publicadores/PrestamoPublish/getNombresLectoresResponse")
    public StringArray getNombresLectores();

}
