
package cliente.modificarEstadoLector;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ModificarEstadoLectorPublish", targetNamespace = "http://publicadores/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ModificarEstadoLectorPublish {


    /**
     * 
     * @param arg1
     * @param arg0
     * @throws LectorNoExisteExcepcion_Exception
     */
    @WebMethod
    @Action(input = "http://publicadores/ModificarEstadoLectorPublish/modificarEstadoLectorRequest", output = "http://publicadores/ModificarEstadoLectorPublish/modificarEstadoLectorResponse", fault = {
        @FaultAction(className = LectorNoExisteExcepcion_Exception.class, value = "http://publicadores/ModificarEstadoLectorPublish/modificarEstadoLector/Fault/LectorNoExisteExcepcion")
    })
    public void modificarEstadoLector(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        EstadoLector arg1)
        throws LectorNoExisteExcepcion_Exception
    ;

    /**
     * 
     * @return
     *     returns cliente.modificarEstadoLector.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/ModificarEstadoLectorPublish/listarNombresLectoresRequest", output = "http://publicadores/ModificarEstadoLectorPublish/listarNombresLectoresResponse")
    public StringArray listarNombresLectores();

    /**
     * 
     * @param arg0
     * @return
     *     returns cliente.modificarEstadoLector.EstadoLector
     * @throws LectorNoExisteExcepcion_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/ModificarEstadoLectorPublish/getEstadoLectorRequest", output = "http://publicadores/ModificarEstadoLectorPublish/getEstadoLectorResponse", fault = {
        @FaultAction(className = LectorNoExisteExcepcion_Exception.class, value = "http://publicadores/ModificarEstadoLectorPublish/getEstadoLector/Fault/LectorNoExisteExcepcion")
    })
    public EstadoLector getEstadoLector(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws LectorNoExisteExcepcion_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns cliente.modificarEstadoLector.DtLector
     * @throws LectorNoExisteExcepcion_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/ModificarEstadoLectorPublish/getDtLectorPorCorreoRequest", output = "http://publicadores/ModificarEstadoLectorPublish/getDtLectorPorCorreoResponse", fault = {
        @FaultAction(className = LectorNoExisteExcepcion_Exception.class, value = "http://publicadores/ModificarEstadoLectorPublish/getDtLectorPorCorreo/Fault/LectorNoExisteExcepcion")
    })
    public DtLector getDtLectorPorCorreo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws LectorNoExisteExcepcion_Exception
    ;

}
