
package cliente.modificarEstadoLector;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ModificarEstadoLectorPublishService", targetNamespace = "http://publicadores/", wsdlLocation = "http://localhost:18017/modificarEstadoLector?wsdl")
public class ModificarEstadoLectorPublishService
    extends Service
{

    private final static URL MODIFICARESTADOLECTORPUBLISHSERVICE_WSDL_LOCATION;
    private final static WebServiceException MODIFICARESTADOLECTORPUBLISHSERVICE_EXCEPTION;
    private final static QName MODIFICARESTADOLECTORPUBLISHSERVICE_QNAME = new QName("http://publicadores/", "ModificarEstadoLectorPublishService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:18017/modificarEstadoLector?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MODIFICARESTADOLECTORPUBLISHSERVICE_WSDL_LOCATION = url;
        MODIFICARESTADOLECTORPUBLISHSERVICE_EXCEPTION = e;
    }

    public ModificarEstadoLectorPublishService() {
        super(__getWsdlLocation(), MODIFICARESTADOLECTORPUBLISHSERVICE_QNAME);
    }

    public ModificarEstadoLectorPublishService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MODIFICARESTADOLECTORPUBLISHSERVICE_QNAME, features);
    }

    public ModificarEstadoLectorPublishService(URL wsdlLocation) {
        super(wsdlLocation, MODIFICARESTADOLECTORPUBLISHSERVICE_QNAME);
    }

    public ModificarEstadoLectorPublishService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MODIFICARESTADOLECTORPUBLISHSERVICE_QNAME, features);
    }

    public ModificarEstadoLectorPublishService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ModificarEstadoLectorPublishService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ModificarEstadoLectorPublish
     */
    @WebEndpoint(name = "ModificarEstadoLectorPublishPort")
    public ModificarEstadoLectorPublish getModificarEstadoLectorPublishPort() {
        return super.getPort(new QName("http://publicadores/", "ModificarEstadoLectorPublishPort"), ModificarEstadoLectorPublish.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ModificarEstadoLectorPublish
     */
    @WebEndpoint(name = "ModificarEstadoLectorPublishPort")
    public ModificarEstadoLectorPublish getModificarEstadoLectorPublishPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://publicadores/", "ModificarEstadoLectorPublishPort"), ModificarEstadoLectorPublish.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MODIFICARESTADOLECTORPUBLISHSERVICE_EXCEPTION!= null) {
            throw MODIFICARESTADOLECTORPUBLISHSERVICE_EXCEPTION;
        }
        return MODIFICARESTADOLECTORPUBLISHSERVICE_WSDL_LOCATION;
    }

}
