
package cliente.modificarEstadoPrestamo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ModificarEstadoPrestamoPublishService", targetNamespace = "http://publicadores/", wsdlLocation = "http://localhost:18026/modificarEstadoPrestamo?wsdl")
public class ModificarEstadoPrestamoPublishService
    extends Service
{

    private final static URL MODIFICARESTADOPRESTAMOPUBLISHSERVICE_WSDL_LOCATION;
    private final static WebServiceException MODIFICARESTADOPRESTAMOPUBLISHSERVICE_EXCEPTION;
    private final static QName MODIFICARESTADOPRESTAMOPUBLISHSERVICE_QNAME = new QName("http://publicadores/", "ModificarEstadoPrestamoPublishService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:18026/modificarEstadoPrestamo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MODIFICARESTADOPRESTAMOPUBLISHSERVICE_WSDL_LOCATION = url;
        MODIFICARESTADOPRESTAMOPUBLISHSERVICE_EXCEPTION = e;
    }

    public ModificarEstadoPrestamoPublishService() {
        super(__getWsdlLocation(), MODIFICARESTADOPRESTAMOPUBLISHSERVICE_QNAME);
    }

    public ModificarEstadoPrestamoPublishService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MODIFICARESTADOPRESTAMOPUBLISHSERVICE_QNAME, features);
    }

    public ModificarEstadoPrestamoPublishService(URL wsdlLocation) {
        super(wsdlLocation, MODIFICARESTADOPRESTAMOPUBLISHSERVICE_QNAME);
    }

    public ModificarEstadoPrestamoPublishService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MODIFICARESTADOPRESTAMOPUBLISHSERVICE_QNAME, features);
    }

    public ModificarEstadoPrestamoPublishService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ModificarEstadoPrestamoPublishService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ModificarEstadoPrestamoPublish
     */
    @WebEndpoint(name = "ModificarEstadoPrestamoPublishPort")
    public ModificarEstadoPrestamoPublish getModificarEstadoPrestamoPublishPort() {
        return super.getPort(new QName("http://publicadores/", "ModificarEstadoPrestamoPublishPort"), ModificarEstadoPrestamoPublish.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ModificarEstadoPrestamoPublish
     */
    @WebEndpoint(name = "ModificarEstadoPrestamoPublishPort")
    public ModificarEstadoPrestamoPublish getModificarEstadoPrestamoPublishPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://publicadores/", "ModificarEstadoPrestamoPublishPort"), ModificarEstadoPrestamoPublish.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MODIFICARESTADOPRESTAMOPUBLISHSERVICE_EXCEPTION!= null) {
            throw MODIFICARESTADOPRESTAMOPUBLISHSERVICE_EXCEPTION;
        }
        return MODIFICARESTADOPRESTAMOPUBLISHSERVICE_WSDL_LOCATION;
    }

}
