
package cliente.modificarEstadoPrestamo;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ModificarEstadoPrestamoPublish", targetNamespace = "http://publicadores/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ModificarEstadoPrestamoPublish {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicadores/ModificarEstadoPrestamoPublish/modificarEstadoPrestamoRequest", output = "http://publicadores/ModificarEstadoPrestamoPublish/modificarEstadoPrestamoResponse")
    public void modificarEstadoPrestamo(
        @WebParam(name = "arg0", partName = "arg0")
        long arg0,
        @WebParam(name = "arg1", partName = "arg1")
        EstadoPmo arg1);

    /**
     * 
     * @return
     *     returns cliente.modificarEstadoPrestamo.DtPrestamoArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/ModificarEstadoPrestamoPublish/listarPrestamosRequest", output = "http://publicadores/ModificarEstadoPrestamoPublish/listarPrestamosResponse")
    public DtPrestamoArray listarPrestamos();

}
