
package cliente.autorizarPrestamo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AutorizarPrestamoPublishService", targetNamespace = "http://publicadores/", wsdlLocation = "http://localhost:18029/autorizarPrestamo?wsdl")
public class AutorizarPrestamoPublishService
    extends Service
{

    private final static URL AUTORIZARPRESTAMOPUBLISHSERVICE_WSDL_LOCATION;
    private final static WebServiceException AUTORIZARPRESTAMOPUBLISHSERVICE_EXCEPTION;
    private final static QName AUTORIZARPRESTAMOPUBLISHSERVICE_QNAME = new QName("http://publicadores/", "AutorizarPrestamoPublishService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:18029/autorizarPrestamo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUTORIZARPRESTAMOPUBLISHSERVICE_WSDL_LOCATION = url;
        AUTORIZARPRESTAMOPUBLISHSERVICE_EXCEPTION = e;
    }

    public AutorizarPrestamoPublishService() {
        super(__getWsdlLocation(), AUTORIZARPRESTAMOPUBLISHSERVICE_QNAME);
    }

    public AutorizarPrestamoPublishService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTORIZARPRESTAMOPUBLISHSERVICE_QNAME, features);
    }

    public AutorizarPrestamoPublishService(URL wsdlLocation) {
        super(wsdlLocation, AUTORIZARPRESTAMOPUBLISHSERVICE_QNAME);
    }

    public AutorizarPrestamoPublishService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUTORIZARPRESTAMOPUBLISHSERVICE_QNAME, features);
    }

    public AutorizarPrestamoPublishService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AutorizarPrestamoPublishService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AutorizarPrestamoPublish
     */
    @WebEndpoint(name = "AutorizarPrestamoPublishPort")
    public AutorizarPrestamoPublish getAutorizarPrestamoPublishPort() {
        return super.getPort(new QName("http://publicadores/", "AutorizarPrestamoPublishPort"), AutorizarPrestamoPublish.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AutorizarPrestamoPublish
     */
    @WebEndpoint(name = "AutorizarPrestamoPublishPort")
    public AutorizarPrestamoPublish getAutorizarPrestamoPublishPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://publicadores/", "AutorizarPrestamoPublishPort"), AutorizarPrestamoPublish.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTORIZARPRESTAMOPUBLISHSERVICE_EXCEPTION!= null) {
            throw AUTORIZARPRESTAMOPUBLISHSERVICE_EXCEPTION;
        }
        return AUTORIZARPRESTAMOPUBLISHSERVICE_WSDL_LOCATION;
    }

}
