
package cliente.autorizarPrestamo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AutorizarPrestamoPublish", targetNamespace = "http://publicadores/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AutorizarPrestamoPublish {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicadores/AutorizarPrestamoPublish/autorizarPrestamoRequest", output = "http://publicadores/AutorizarPrestamoPublish/autorizarPrestamoResponse")
    public void autorizarPrestamo(
        @WebParam(name = "arg0", partName = "arg0")
        long arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @return
     *     returns cliente.autorizarPrestamo.DtPrestamoArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/AutorizarPrestamoPublish/listarPrestamosPendientesRequest", output = "http://publicadores/AutorizarPrestamoPublish/listarPrestamosPendientesResponse")
    public DtPrestamoArray listarPrestamosPendientes();

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicadores/AutorizarPrestamoPublish/rechazarPrestamoRequest", output = "http://publicadores/AutorizarPrestamoPublish/rechazarPrestamoResponse")
    public void rechazarPrestamo(
        @WebParam(name = "arg0", partName = "arg0")
        long arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

}
