
package cliente.consultaDonacionYFecha;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConsultaDonacionYFechaPublishService", targetNamespace = "http://publicadores/", wsdlLocation = "http://localhost:18024/consultaDonacionYFecha?wsdl")
public class ConsultaDonacionYFechaPublishService
    extends Service
{

    private final static URL CONSULTADONACIONYFECHAPUBLISHSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONSULTADONACIONYFECHAPUBLISHSERVICE_EXCEPTION;
    private final static QName CONSULTADONACIONYFECHAPUBLISHSERVICE_QNAME = new QName("http://publicadores/", "ConsultaDonacionYFechaPublishService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:18024/consultaDonacionYFecha?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTADONACIONYFECHAPUBLISHSERVICE_WSDL_LOCATION = url;
        CONSULTADONACIONYFECHAPUBLISHSERVICE_EXCEPTION = e;
    }

    public ConsultaDonacionYFechaPublishService() {
        super(__getWsdlLocation(), CONSULTADONACIONYFECHAPUBLISHSERVICE_QNAME);
    }

    public ConsultaDonacionYFechaPublishService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTADONACIONYFECHAPUBLISHSERVICE_QNAME, features);
    }

    public ConsultaDonacionYFechaPublishService(URL wsdlLocation) {
        super(wsdlLocation, CONSULTADONACIONYFECHAPUBLISHSERVICE_QNAME);
    }

    public ConsultaDonacionYFechaPublishService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTADONACIONYFECHAPUBLISHSERVICE_QNAME, features);
    }

    public ConsultaDonacionYFechaPublishService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaDonacionYFechaPublishService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsultaDonacionYFechaPublish
     */
    @WebEndpoint(name = "ConsultaDonacionYFechaPublishPort")
    public ConsultaDonacionYFechaPublish getConsultaDonacionYFechaPublishPort() {
        return super.getPort(new QName("http://publicadores/", "ConsultaDonacionYFechaPublishPort"), ConsultaDonacionYFechaPublish.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaDonacionYFechaPublish
     */
    @WebEndpoint(name = "ConsultaDonacionYFechaPublishPort")
    public ConsultaDonacionYFechaPublish getConsultaDonacionYFechaPublishPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://publicadores/", "ConsultaDonacionYFechaPublishPort"), ConsultaDonacionYFechaPublish.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTADONACIONYFECHAPUBLISHSERVICE_EXCEPTION!= null) {
            throw CONSULTADONACIONYFECHAPUBLISHSERVICE_EXCEPTION;
        }
        return CONSULTADONACIONYFECHAPUBLISHSERVICE_WSDL_LOCATION;
    }

}
