
package cliente.donaciones;

import jakarta.jws.WebMethod;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ControladorDonacionesPublish", targetNamespace = "http://publicadores/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ControladorDonacionesPublish {


    /**
     * 
     * @return
     *     returns cliente.donaciones.DtMaterialArray
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/ControladorDonacionesPublish/obtenerDonacionesRequest", output = "http://publicadores/ControladorDonacionesPublish/obtenerDonacionesResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://publicadores/ControladorDonacionesPublish/obtenerDonaciones/Fault/Exception")
    })
    public DtMaterialArray obtenerDonaciones()
        throws Exception_Exception
    ;

}
