
package cliente.donaciones;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ControladorDonacionesPublishService", targetNamespace = "http://publicadores/", wsdlLocation = "http://localhost:18019/donaciones?wsdl")
public class ControladorDonacionesPublishService
    extends Service
{

    private final static URL CONTROLADORDONACIONESPUBLISHSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONTROLADORDONACIONESPUBLISHSERVICE_EXCEPTION;
    private final static QName CONTROLADORDONACIONESPUBLISHSERVICE_QNAME = new QName("http://publicadores/", "ControladorDonacionesPublishService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:18019/donaciones?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONTROLADORDONACIONESPUBLISHSERVICE_WSDL_LOCATION = url;
        CONTROLADORDONACIONESPUBLISHSERVICE_EXCEPTION = e;
    }

    public ControladorDonacionesPublishService() {
        super(__getWsdlLocation(), CONTROLADORDONACIONESPUBLISHSERVICE_QNAME);
    }

    public ControladorDonacionesPublishService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTROLADORDONACIONESPUBLISHSERVICE_QNAME, features);
    }

    public ControladorDonacionesPublishService(URL wsdlLocation) {
        super(wsdlLocation, CONTROLADORDONACIONESPUBLISHSERVICE_QNAME);
    }

    public ControladorDonacionesPublishService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTROLADORDONACIONESPUBLISHSERVICE_QNAME, features);
    }

    public ControladorDonacionesPublishService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ControladorDonacionesPublishService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ControladorDonacionesPublish
     */
    @WebEndpoint(name = "ControladorDonacionesPublishPort")
    public ControladorDonacionesPublish getControladorDonacionesPublishPort() {
        return super.getPort(new QName("http://publicadores/", "ControladorDonacionesPublishPort"), ControladorDonacionesPublish.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ControladorDonacionesPublish
     */
    @WebEndpoint(name = "ControladorDonacionesPublishPort")
    public ControladorDonacionesPublish getControladorDonacionesPublishPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://publicadores/", "ControladorDonacionesPublishPort"), ControladorDonacionesPublish.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTROLADORDONACIONESPUBLISHSERVICE_EXCEPTION!= null) {
            throw CONTROLADORDONACIONESPUBLISHSERVICE_EXCEPTION;
        }
        return CONTROLADORDONACIONESPUBLISHSERVICE_WSDL_LOCATION;
    }

}
