
package cliente.altaLector;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AltaLectorPublishService", targetNamespace = "http://publicadores/", wsdlLocation = "http://localhost:18015/altaLector?wsdl")
public class AltaLectorPublishService
    extends Service
{

    private final static URL ALTALECTORPUBLISHSERVICE_WSDL_LOCATION;
    private final static WebServiceException ALTALECTORPUBLISHSERVICE_EXCEPTION;
    private final static QName ALTALECTORPUBLISHSERVICE_QNAME = new QName("http://publicadores/", "AltaLectorPublishService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:18015/altaLector?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ALTALECTORPUBLISHSERVICE_WSDL_LOCATION = url;
        ALTALECTORPUBLISHSERVICE_EXCEPTION = e;
    }

    public AltaLectorPublishService() {
        super(__getWsdlLocation(), ALTALECTORPUBLISHSERVICE_QNAME);
    }

    public AltaLectorPublishService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ALTALECTORPUBLISHSERVICE_QNAME, features);
    }

    public AltaLectorPublishService(URL wsdlLocation) {
        super(wsdlLocation, ALTALECTORPUBLISHSERVICE_QNAME);
    }

    public AltaLectorPublishService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ALTALECTORPUBLISHSERVICE_QNAME, features);
    }

    public AltaLectorPublishService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AltaLectorPublishService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AltaLectorPublish
     */
    @WebEndpoint(name = "AltaLectorPublishPort")
    public AltaLectorPublish getAltaLectorPublishPort() {
        return super.getPort(new QName("http://publicadores/", "AltaLectorPublishPort"), AltaLectorPublish.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AltaLectorPublish
     */
    @WebEndpoint(name = "AltaLectorPublishPort")
    public AltaLectorPublish getAltaLectorPublishPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://publicadores/", "AltaLectorPublishPort"), AltaLectorPublish.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ALTALECTORPUBLISHSERVICE_EXCEPTION!= null) {
            throw ALTALECTORPUBLISHSERVICE_EXCEPTION;
        }
        return ALTALECTORPUBLISHSERVICE_WSDL_LOCATION;
    }

}
