
package cliente.altaDonacionLibro;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AltaDonacionLibroPublishService", targetNamespace = "http://publicadores/", wsdlLocation = "http://localhost:18021/altaDonacionLibro?wsdl")
public class AltaDonacionLibroPublishService
    extends Service
{

    private final static URL ALTADONACIONLIBROPUBLISHSERVICE_WSDL_LOCATION;
    private final static WebServiceException ALTADONACIONLIBROPUBLISHSERVICE_EXCEPTION;
    private final static QName ALTADONACIONLIBROPUBLISHSERVICE_QNAME = new QName("http://publicadores/", "AltaDonacionLibroPublishService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:18021/altaDonacionLibro?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ALTADONACIONLIBROPUBLISHSERVICE_WSDL_LOCATION = url;
        ALTADONACIONLIBROPUBLISHSERVICE_EXCEPTION = e;
    }

    public AltaDonacionLibroPublishService() {
        super(__getWsdlLocation(), ALTADONACIONLIBROPUBLISHSERVICE_QNAME);
    }

    public AltaDonacionLibroPublishService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ALTADONACIONLIBROPUBLISHSERVICE_QNAME, features);
    }

    public AltaDonacionLibroPublishService(URL wsdlLocation) {
        super(wsdlLocation, ALTADONACIONLIBROPUBLISHSERVICE_QNAME);
    }

    public AltaDonacionLibroPublishService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ALTADONACIONLIBROPUBLISHSERVICE_QNAME, features);
    }

    public AltaDonacionLibroPublishService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AltaDonacionLibroPublishService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AltaDonacionLibroPublish
     */
    @WebEndpoint(name = "AltaDonacionLibroPublishPort")
    public AltaDonacionLibroPublish getAltaDonacionLibroPublishPort() {
        return super.getPort(new QName("http://publicadores/", "AltaDonacionLibroPublishPort"), AltaDonacionLibroPublish.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AltaDonacionLibroPublish
     */
    @WebEndpoint(name = "AltaDonacionLibroPublishPort")
    public AltaDonacionLibroPublish getAltaDonacionLibroPublishPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://publicadores/", "AltaDonacionLibroPublishPort"), AltaDonacionLibroPublish.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ALTADONACIONLIBROPUBLISHSERVICE_EXCEPTION!= null) {
            throw ALTADONACIONLIBROPUBLISHSERVICE_EXCEPTION;
        }
        return ALTADONACIONLIBROPUBLISHSERVICE_WSDL_LOCATION;
    }

}
