
package cliente.altaDonacionLibro;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "AltaDonacionEspecialPublish", targetNamespace = "http://publicadores/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AltaDonacionEspecialPublish {


    /**
     * 
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @Action(input = "http://publicadores/AltaDonacionEspecialPublish/altaDonacionEspecialRequest", output = "http://publicadores/AltaDonacionEspecialPublish/altaDonacionEspecialResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://publicadores/AltaDonacionEspecialPublish/altaDonacionEspecial/Fault/Exception")
    })
    public void altaDonacionEspecial(
        @WebParam(name = "arg0", partName = "arg0")
        DtArticuloEspecial arg0)
        throws Exception_Exception
    ;

}
