
package cliente.listarPrestamosLector;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ListarPrestamosLectorPublish", targetNamespace = "http://publicadores/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ListarPrestamosLectorPublish {


    /**
     * 
     * @param arg0
     * @return
     *     returns cliente.listarPrestamosLector.DtPrestamoArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/ListarPrestamosLectorPublish/listarPrestamosActivosLectorRequest", output = "http://publicadores/ListarPrestamosLectorPublish/listarPrestamosActivosLectorResponse")
    public DtPrestamoArray listarPrestamosActivosLector(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns cliente.listarPrestamosLector.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/ListarPrestamosLectorPublish/obtenerNombresLectoresRequest", output = "http://publicadores/ListarPrestamosLectorPublish/obtenerNombresLectoresResponse")
    public StringArray obtenerNombresLectores();

    /**
     * 
     * @param arg0
     * @return
     *     returns cliente.listarPrestamosLector.DtPrestamoArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/ListarPrestamosLectorPublish/listarTodosPrestamosLectorRequest", output = "http://publicadores/ListarPrestamosLectorPublish/listarTodosPrestamosLectorResponse")
    public DtPrestamoArray listarTodosPrestamosLector(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
