
package cliente.listarPrestamosLector;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ListarPrestamosLectorPublishService", targetNamespace = "http://publicadores/", wsdlLocation = "http://localhost:18025/listarPrestamosLector?wsdl")
public class ListarPrestamosLectorPublishService
    extends Service
{

    private final static URL LISTARPRESTAMOSLECTORPUBLISHSERVICE_WSDL_LOCATION;
    private final static WebServiceException LISTARPRESTAMOSLECTORPUBLISHSERVICE_EXCEPTION;
    private final static QName LISTARPRESTAMOSLECTORPUBLISHSERVICE_QNAME = new QName("http://publicadores/", "ListarPrestamosLectorPublishService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:18025/listarPrestamosLector?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LISTARPRESTAMOSLECTORPUBLISHSERVICE_WSDL_LOCATION = url;
        LISTARPRESTAMOSLECTORPUBLISHSERVICE_EXCEPTION = e;
    }

    public ListarPrestamosLectorPublishService() {
        super(__getWsdlLocation(), LISTARPRESTAMOSLECTORPUBLISHSERVICE_QNAME);
    }

    public ListarPrestamosLectorPublishService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LISTARPRESTAMOSLECTORPUBLISHSERVICE_QNAME, features);
    }

    public ListarPrestamosLectorPublishService(URL wsdlLocation) {
        super(wsdlLocation, LISTARPRESTAMOSLECTORPUBLISHSERVICE_QNAME);
    }

    public ListarPrestamosLectorPublishService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LISTARPRESTAMOSLECTORPUBLISHSERVICE_QNAME, features);
    }

    public ListarPrestamosLectorPublishService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ListarPrestamosLectorPublishService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ListarPrestamosLectorPublish
     */
    @WebEndpoint(name = "ListarPrestamosLectorPublishPort")
    public ListarPrestamosLectorPublish getListarPrestamosLectorPublishPort() {
        return super.getPort(new QName("http://publicadores/", "ListarPrestamosLectorPublishPort"), ListarPrestamosLectorPublish.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ListarPrestamosLectorPublish
     */
    @WebEndpoint(name = "ListarPrestamosLectorPublishPort")
    public ListarPrestamosLectorPublish getListarPrestamosLectorPublishPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://publicadores/", "ListarPrestamosLectorPublishPort"), ListarPrestamosLectorPublish.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LISTARPRESTAMOSLECTORPUBLISHSERVICE_EXCEPTION!= null) {
            throw LISTARPRESTAMOSLECTORPUBLISHSERVICE_EXCEPTION;
        }
        return LISTARPRESTAMOSLECTORPUBLISHSERVICE_WSDL_LOCATION;
    }

}
