
package cliente.consultarDonacion;

import jakarta.jws.WebMethod;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ConsultarDonacionPublish", targetNamespace = "http://publicadores/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConsultarDonacionPublish {


    /**
     * 
     * @return
     *     returns cliente.consultarDonacion.DtMaterialArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/ConsultarDonacionPublish/consultarDonacionRequest", output = "http://publicadores/ConsultarDonacionPublish/consultarDonacionResponse")
    public DtMaterialArray consultarDonacion();

}
