
package cliente.consultarDonacion;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConsultarDonacionPublishService", targetNamespace = "http://publicadores/", wsdlLocation = "http://localhost:18023/consultarDonacion?wsdl")
public class ConsultarDonacionPublishService
    extends Service
{

    private final static URL CONSULTARDONACIONPUBLISHSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONSULTARDONACIONPUBLISHSERVICE_EXCEPTION;
    private final static QName CONSULTARDONACIONPUBLISHSERVICE_QNAME = new QName("http://publicadores/", "ConsultarDonacionPublishService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:18023/consultarDonacion?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTARDONACIONPUBLISHSERVICE_WSDL_LOCATION = url;
        CONSULTARDONACIONPUBLISHSERVICE_EXCEPTION = e;
    }

    public ConsultarDonacionPublishService() {
        super(__getWsdlLocation(), CONSULTARDONACIONPUBLISHSERVICE_QNAME);
    }

    public ConsultarDonacionPublishService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTARDONACIONPUBLISHSERVICE_QNAME, features);
    }

    public ConsultarDonacionPublishService(URL wsdlLocation) {
        super(wsdlLocation, CONSULTARDONACIONPUBLISHSERVICE_QNAME);
    }

    public ConsultarDonacionPublishService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTARDONACIONPUBLISHSERVICE_QNAME, features);
    }

    public ConsultarDonacionPublishService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultarDonacionPublishService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsultarDonacionPublish
     */
    @WebEndpoint(name = "ConsultarDonacionPublishPort")
    public ConsultarDonacionPublish getConsultarDonacionPublishPort() {
        return super.getPort(new QName("http://publicadores/", "ConsultarDonacionPublishPort"), ConsultarDonacionPublish.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultarDonacionPublish
     */
    @WebEndpoint(name = "ConsultarDonacionPublishPort")
    public ConsultarDonacionPublish getConsultarDonacionPublishPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://publicadores/", "ConsultarDonacionPublishPort"), ConsultarDonacionPublish.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTARDONACIONPUBLISHSERVICE_EXCEPTION!= null) {
            throw CONSULTARDONACIONPUBLISHSERVICE_EXCEPTION;
        }
        return CONSULTARDONACIONPUBLISHSERVICE_WSDL_LOCATION;
    }

}
