
package cliente.consultarDonacion;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConsultarDonacionPublish", targetNamespace = "http://publicadores/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConsultarDonacionPublish {


    /**
     * 
     * @return
     *     returns cliente.consultarDonacion.DtMaterialArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/ConsultarDonacionPublish/consultarDonacionRequest", output = "http://publicadores/ConsultarDonacionPublish/consultarDonacionResponse")
    public DtMaterialArray consultarDonacion();

}
