
package cliente.login;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "LoginPublishService", targetNamespace = "http://publicadores/", wsdlLocation = "http://localhost:18016/login?wsdl")
public class LoginPublishService
    extends Service
{

    private final static URL LOGINPUBLISHSERVICE_WSDL_LOCATION;
    private final static WebServiceException LOGINPUBLISHSERVICE_EXCEPTION;
    private final static QName LOGINPUBLISHSERVICE_QNAME = new QName("http://publicadores/", "LoginPublishService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:18016/login?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOGINPUBLISHSERVICE_WSDL_LOCATION = url;
        LOGINPUBLISHSERVICE_EXCEPTION = e;
    }

    public LoginPublishService() {
        super(__getWsdlLocation(), LOGINPUBLISHSERVICE_QNAME);
    }

    public LoginPublishService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOGINPUBLISHSERVICE_QNAME, features);
    }

    public LoginPublishService(URL wsdlLocation) {
        super(wsdlLocation, LOGINPUBLISHSERVICE_QNAME);
    }

    public LoginPublishService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOGINPUBLISHSERVICE_QNAME, features);
    }

    public LoginPublishService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LoginPublishService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LoginPublish
     */
    @WebEndpoint(name = "LoginPublishPort")
    public LoginPublish getLoginPublishPort() {
        return super.getPort(new QName("http://publicadores/", "LoginPublishPort"), LoginPublish.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoginPublish
     */
    @WebEndpoint(name = "LoginPublishPort")
    public LoginPublish getLoginPublishPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://publicadores/", "LoginPublishPort"), LoginPublish.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOGINPUBLISHSERVICE_EXCEPTION!= null) {
            throw LOGINPUBLISHSERVICE_EXCEPTION;
        }
        return LOGINPUBLISHSERVICE_WSDL_LOCATION;
    }

}
