
package cliente.login;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LoginPublish", targetNamespace = "http://publicadores/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LoginPublish {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns cliente.login.DtLoginResultado
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/LoginPublish/loginRequest", output = "http://publicadores/LoginPublish/loginResponse")
    public DtLoginResultado login(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

}
