
package cliente.login;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "LoginPublish", targetNamespace = "http://publicadores/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LoginPublish {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns cliente.login.DtLoginResultado
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/LoginPublish/loginRequest", output = "http://publicadores/LoginPublish/loginResponse")
    public DtLoginResultado login(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

}
