
package cliente.modificarZonaLector;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "LectorNoExisteExcepcion", targetNamespace = "http://publicadores/")
public class LectorNoExisteExcepcion_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private LectorNoExisteExcepcion faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public LectorNoExisteExcepcion_Exception(String message, LectorNoExisteExcepcion faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public LectorNoExisteExcepcion_Exception(String message, LectorNoExisteExcepcion faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: cliente.modificarZonaLector.LectorNoExisteExcepcion
     */
    public LectorNoExisteExcepcion getFaultInfo() {
        return faultInfo;
    }

}
