
package cliente.modificarZonaLector;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ModificarZonaLectorPublishService", targetNamespace = "http://publicadores/", wsdlLocation = "http://localhost:18018/modificarZonaLector?wsdl")
public class ModificarZonaLectorPublishService
    extends Service
{

    private final static URL MODIFICARZONALECTORPUBLISHSERVICE_WSDL_LOCATION;
    private final static WebServiceException MODIFICARZONALECTORPUBLISHSERVICE_EXCEPTION;
    private final static QName MODIFICARZONALECTORPUBLISHSERVICE_QNAME = new QName("http://publicadores/", "ModificarZonaLectorPublishService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:18018/modificarZonaLector?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MODIFICARZONALECTORPUBLISHSERVICE_WSDL_LOCATION = url;
        MODIFICARZONALECTORPUBLISHSERVICE_EXCEPTION = e;
    }

    public ModificarZonaLectorPublishService() {
        super(__getWsdlLocation(), MODIFICARZONALECTORPUBLISHSERVICE_QNAME);
    }

    public ModificarZonaLectorPublishService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MODIFICARZONALECTORPUBLISHSERVICE_QNAME, features);
    }

    public ModificarZonaLectorPublishService(URL wsdlLocation) {
        super(wsdlLocation, MODIFICARZONALECTORPUBLISHSERVICE_QNAME);
    }

    public ModificarZonaLectorPublishService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MODIFICARZONALECTORPUBLISHSERVICE_QNAME, features);
    }

    public ModificarZonaLectorPublishService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ModificarZonaLectorPublishService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ModificarZonaLectorPublish
     */
    @WebEndpoint(name = "ModificarZonaLectorPublishPort")
    public ModificarZonaLectorPublish getModificarZonaLectorPublishPort() {
        return super.getPort(new QName("http://publicadores/", "ModificarZonaLectorPublishPort"), ModificarZonaLectorPublish.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ModificarZonaLectorPublish
     */
    @WebEndpoint(name = "ModificarZonaLectorPublishPort")
    public ModificarZonaLectorPublish getModificarZonaLectorPublishPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://publicadores/", "ModificarZonaLectorPublishPort"), ModificarZonaLectorPublish.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MODIFICARZONALECTORPUBLISHSERVICE_EXCEPTION!= null) {
            throw MODIFICARZONALECTORPUBLISHSERVICE_EXCEPTION;
        }
        return MODIFICARZONALECTORPUBLISHSERVICE_WSDL_LOCATION;
    }

}
